#! /bin/sh
#
# This is an init script for Debian Sid
# Copy it to /etc/init.d/lirc and type
# > update-rc.d lirc defaults 20
#


test -f /usr/sbin/lircd || exit 0

case "$1" in
  start)
    # in case your lirc dev points are not created automatically, the next
    # line will create them.
    test -c /dev/lirc-mce || (mkdir -p -- . /dev && /bin/mknod /dev/lirc-mce c 61 0)
    mkdir /run/lirc
    echo -n "Starting lirc daemon: lircd"
    start-stop-daemon --start --quiet --exec /usr/sbin/lircd -- --device=/dev/lirc-mce
    echo "."
    ;;
  stop)
    echo -n "Stopping lirc daemon: lircd"
    start-stop-daemon --stop --quiet --exec /usr/sbin/lircd
    echo "."
    ;;
  reload|force-reload)
    start-stop-daemon --stop --quiet --signal 1 --exec /usr/sbin/lircd
    ;;
  restart)
    echo -n "Stopping lirc daemon: lircd"
    start-stop-daemon --stop --quiet --exec /usr/sbin/lircd
    sleep 1
    echo -n "Starting lirc daemon: lircd"
    start-stop-daemon --start --quiet --exec /usr/sbin/lircd -- --device=/dev/lirc-mce
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/lircd {start|stop|reload|restart|force-reload}"
    exit 1
esac

exit 0
